version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data

    db:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: soemthing
            MYSQL_DATABASE: developer_portal
            MYSQL_USER: developer_portal
            MYSQL_PASSWORD: developer_portal

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8001:80"
        depends_on:
            - db
        environment:
            PMA_HOST: db

    testdb:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: soemthing
            MYSQL_DATABASE: test
            MYSQL_USER: developer_portal
            MYSQL_PASSWORD: developer_portal

    web:
        build: .
        volumes_from:
            - data
        ports:
            - "80:80"
        links:
            - db
            - proxy:apiaxle.api.proxy
            - proxy:test.api.proxy
        env_file:
            - ./common.env
            - ./local.env

    composer:
        image: silintl/php7:7.2
        volumes_from:
            - data
        working_dir: /data
        command: composer install --no-scripts

    composerupdate:
        image: silintl/php7:7.2
        volumes_from:
            - data
        working_dir: /data
        command: composer update --no-scripts

    yiimigrate:
        image: silintl/php7:7.2
        volumes_from:
            - data
        links:
            - db
        env_file:
            - ./common.env
            - ./local.env
        working_dir: /data/protected
        command: bash -c "whenavail db 3306 100 ./yiic migrate --interactive=0"

    yiimigratetestdb:
        image: silintl/php7:7.2
        volumes_from:
            - data
        links:
            - testdb
        env_file:
            - ./common.env
            - ./local.env
        working_dir: /data/protected
        command: whenavail testdb 3306 100 ./yiic migrate --interactive=0
        environment:
          MYSQL_HOST: testdb
          MYSQL_DATABASE: test

    phpunit:
        image: silintl/php7:7.2
        volumes_from:
            - data
        links:
            - testdb
            - proxy:apiaxle.api.proxy
            - proxy:test.api.proxy
            - web:developer-portal.local
        env_file:
            - ./common.env
            - ./local.env
        working_dir: /data/protected/tests
        command: whenavail testdb 3306 100 ../../vendor/bin/phpunit --testsuite DeveloperPortal
        environment:
          MYSQL_HOST: testdb
          MYSQL_DATABASE: test
          SAML_ADMIN_PASSWORD: dummy-for-tests-q6.eYWtfLF-BTQXf-OktD5lVFCOFyC4B
          SAML_SECRET_SALT: dummy-for-tests-Ac4MTgO9UJ6_wpXXKc6EGU_.gWNNkdMe
          SAML_IDP: NONE

    redis:
        image: redis:latest

    api:
        image: apiaxle/apiaxle:1.15.0
        links:
            - redis
        ports:
            - "80"
        command: api 80

    proxy:
        image: apiaxle/apiaxle:1.15.0
        links:
            - api
            - redis
        ports:
            - "80"
        command: proxy 80 -q

    axlesetup:
        image: silintl/php7:7.2
        links:
            - api
        env_file:
            -   common.env
        volumes:
            - ./build/setup-apiaxle.sh:/usr/local/bin/setup-apiaxle.sh
        command: setup-apiaxle.sh
